### PR TITLE
Removed the GSS code decoding that is now done...

### PR DESCRIPTION
**Pull request by acron0**
...in witan.r.models 0.1.3-SNAPSHOT

Also removed the test model as it's outdated.

### CODE REVIEW

**Comment by acron0** [comment]
Here is the new code in witan.r.models for reference: https://github.com/MastodonC/witan.r.models/blob/master/src/clj/witan/models.clj#L456

**Comment by elisehuard** [comment]
:shipit:

**Comment by sw1nn** [comment]
What's the motivation for this change. It seems to me that the borough code is the identity of the borough and the name is a presentation detail.

**Comment by sw1nn** [comment]
so the lookup from code -> borough should be in the client, the model shoudn't care what the name is. Consider the case where the UI  might render the name differently for different clients (PC vs tablet)

**Comment by acron0** [comment]
@sw1nn Your assumption about presentation. The borough name in this context is not determined by the UI, it's a "property" defined by the model itself. This change is insulating the "model execution" from handling what is an essentially an arbitrary property defined by one of the models.

**Comment by sw1nn** [comment]
The name should not be a property defined by the model. It absolutely should be determined by the ui. Possibly there should be a reference data service that maps 'property values' -> display value. I expect there will be other values other than name that will need this treatment.

**Comment by acron0** [comment]
@sw1nn The UI isn't going to do that because it has no concept of boroughs, because boroughs are something specific to one model - as all properties defined by models, the meanings behind them are specific to the parent models. In this case, the alternative would be to expose users to a list of GSS codes but that's a clear violation of good UX.

**Comment by sw1nn** [comment]
No, the alternative is to have something that can take model properties and render them for display. This is but the first example of when this will need to be done.

**Comment by acron0** [comment]
@sw1nn Another alternative could be allowing the model to specify "value" and "name" properties in the list here, rather than *just* names: https://github.com/MastodonC/witan.app/blob/master/src/witan/app/test_data.clj#L86

But either way, the *model* is the one in charge of the visual, regardless of where the name->value conversion is done.

**Comment by acron0** [comment]
@sw1nn Model properties exist within a framework we've designed which facilitates how they are rendered. You can see an example [here] (https://github.com/MastodonC/witan.app/blob/master/src/witan/app/test_data.clj#L83).

**Comment by acron0** [comment]
It was agreed on a hangout to merge this but revisit the idea of model property presentation at some point.

**Pull request merged**
