### PR TITLE
Add updated copy

### PR DESCRIPTION
**Pull request by mrchrisadams**
I've tried to keep the essence of the guidance, but we link back to a blog post on the Witan Bulletin blog with more details, so if it still looks too long, we can probably pare it back a bit further, as long as we can direct people somewhere for more details.

### CODE REVIEW

**Comment by mrchrisadams** [comment]
This is a bit of pain to look at, so here's the copy below:

For the housing linked model:

------------

Two variants of this model differ in how borough-level populations are generated, but both use the ward model to distribute these between wards.

### DCLG variant
This model adjusts domestic migration assumptions until it arrives at a borough-level population that fits the available dwelling stock. This model is useful in areas where housing development is expected to be the predominant driver in future population change.  Projections produced by this model will usually imply falling household size.

### Capped Household Size variant
This model attempts to account for both recent trends in population change and future changes in housing stock. This is the GLA’s general use model and provides more intuitive results across a wider range of scenarios than either the trend-based model or DCLG variant of the housing linked model.

#### Which fertility assumption?

The models are initiated with fertility rates for each borough and ward based on recent birth estimates.  These are then projected forward using trends taken from the 2014-based National Population projections for England.

- *Standard* – fertility relative to 2014 rises by 4% over the next decade before levelling off
- *Low* – fertility relative to 2014 falls by 6.5% over the next decade before levelling off.
- *High* – fertility relative to 2014 rises by 13% over the next decade and then rises at a slower rate to reach a level 15% higher by 2040.


##### Further info

Further explanation of the difference between GLA population projection variants [can be found here](https://files.datapress.com/london/dataset/2013-round-population-projections/technical-note-guide-gla-popproj-variants.pdf).

----------

## For the trend based model

----------


This model uses projections of the overall borough-level population from the GLA’s trend-based cohort-component model.  The overall population is independent of the assumed housing trajectory.

Ward level projections are constrained to match the overall borough-level population, but the distribution of population between the wards is determined by the housing data input by the user.

This model is most useful in areas where recent population change has occurred largely independently of changes in available housing stock.  In areas where recent population growth outstrips planned housing development, the model results will imply increasing household size.

#### Which fertility assumption?

The models are initiated with fertility rates for each borough and ward based on recent birth estimates.  These are then projected forward using trends taken from the 2014-based National Population projections for England.  The Low, Standard, and High options correspond to the trends from the Low, Principal, and High fertility variants of the national projections.  

- *Standard* – fertility relative to 2014 rises by 4% over the next decade before levelling off
- *Low* – fertility relative to 2014 falls by 6.5% over the next decade before levelling off.
- *High* – fertility relative to 2014 rises by 13% over the next decade and then rises at a slower rate to reach a level 15% higher by 2040.


##### Further info

Further explanation of the difference between GLA population projection variants [can be found here](https://witanbulletin.wordpress.com/2016/03/21/a-brief-guide-to-choosing-your-models-in-witan/).

**Comment by acron0** [comment]
@mrchrisadams The link in each description has a different destination; is that intentional?

**Comment by mrchrisadams** [comment]
Yes, the change in the link description is intentional. Previously we were linking to a PDF, on a domain we could't control.

We now link to a website where we can control the content on it - specifically, [this blog post](https://witanbulletin.wordpress.com/2016/03/21/a-brief-guide-to-choosing-your-models-in-witan/)

**Comment by acron0** [comment]
Sorry, you misunderstood but it's okay as I didn't look at the src, just the one you pasted as a comment. They are different but the src one is fine.

**Comment by mrchrisadams** [comment]
Antony, did you want anything else changed on this before it was in shape to merge in?

**Comment by acron0** [comment]
No mate, hence the :shipit: ;)

**Pull request merged**
