### PR TITLE
Schema changes to ForecastInfo to pass model props + /models/:id

### PR DESCRIPTION
**Pull request by elisehuard**
- Added model properties to the > 0 versions
- refactored a little bit
- service for /models/:id to retrieve model info

The input and output in the Forecast are stubbed to [] at the moment.

### CODE REVIEW

**Comment by acron0** [comment]
lgtm :shipit:

**Comment by acron0** [comment]
Hang fire, `/forecasts/:id/:version` is causing a 500... I am investigating

**Comment by elisehuard** [comment]
also, thinking of setting up some smoke tests (integration tests) where it just calls the REST API directly (using clj-http or something).  This is probably the most effective strategy to avoid regression (short of testing all the things)

**Comment by acron0** [comment]
:shipit:

**Pull request merged**
